export { default as Profile } from './Profile'
export { default as NoticeBoard } from './NoticeBoard'
export { default as TimeBoard } from './TimeBoard'
export { default as SelfStudyBoard } from './SelfStudyBoard'
export { default as MassageBoard } from './MassageBoard'
export { default as MealBoard } from './MealBoard'